# Generated by Django 5.2.16 on 2026-07-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsettings',
            name='faq_title_ar',
            field=models.CharField(default='الأسئلة الشائعة', max_length=160, verbose_name='عنوان الأسئلة بالعربية'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='faq_title_en',
            field=models.CharField(default='FAQ', max_length=160, verbose_name='عنوان الأسئلة بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='featured_title_ar',
            field=models.CharField(default='أطباق مميزة', max_length=160, verbose_name='عنوان الأطباق المميزة بالعربية'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='featured_title_en',
            field=models.CharField(default='Featured Menu', max_length=160, verbose_name='عنوان الأطباق المميزة بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='menu_title_ar',
            field=models.CharField(default='استكشف أقسام القائمة', max_length=160, verbose_name='عنوان أقسام القائمة بالعربية'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='menu_title_en',
            field=models.CharField(default='Explore Our Menu', max_length=160, verbose_name='عنوان أقسام القائمة بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='offers_title_ar',
            field=models.CharField(default='عروض وأطباق مميزة', max_length=160, verbose_name='عنوان العروض بالعربية'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='offers_title_en',
            field=models.CharField(default='Special Offers', max_length=160, verbose_name='عنوان العروض بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='reservation_text_ar',
            field=models.TextField(default='احجز طاولتك بسهولة أو تواصل معنا مباشرة عبر واتساب.', verbose_name='وصف الحجز بالعربية'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='reservation_text_en',
            field=models.TextField(default='Reserve your table easily or contact us directly on WhatsApp.', verbose_name='وصف الحجز بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='reservation_title_ar',
            field=models.CharField(default='احجز طاولتك أو تواصل معنا', max_length=180, verbose_name='عنوان الحجز بالعربية'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='reservation_title_en',
            field=models.CharField(default='Reservation & Contact', max_length=180, verbose_name='عنوان الحجز بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='reviews_title_ar',
            field=models.CharField(default='آراء عملائنا', max_length=160, verbose_name='عنوان التقييمات بالعربية'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='reviews_title_en',
            field=models.CharField(default='Customer Reviews', max_length=160, verbose_name='عنوان التقييمات بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='services_title_ar',
            field=models.CharField(default='خدماتنا', max_length=160, verbose_name='عنوان الخدمات بالعربية'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='services_title_en',
            field=models.CharField(default='Our Services', max_length=160, verbose_name='عنوان الخدمات بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='social_title_ar',
            field=models.CharField(default='تابعنا على إنستغرام', max_length=160, verbose_name='عنوان التواصل الاجتماعي بالعربية'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='social_title_en',
            field=models.CharField(default='Follow Us on Instagram', max_length=160, verbose_name='عنوان التواصل الاجتماعي بالإنجليزية'),
        ),
    ]
