# Generated by Django 5.2.16 on 2026-07-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_validate_design_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsettings',
            name='about_text_ar',
            field=models.TextField(default='وُلد مطعم B12 من شغف حقيقي بالطعم الأصيل. نجمع بين المشاوي الشرقية والأطباق العالمية في مكان واحد، ونحضّر كل طبق يوميًا بمكونات طازجة مختارة بعناية، لنقدم لكم تجربة تستحق التكرار.', verbose_name='نص من نحن بالعربية'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='about_text_en',
            field=models.TextField(default='B12 was born from a real passion for authentic flavour. We bring oriental grills and international dishes together under one roof, preparing every dish daily with carefully selected fresh ingredients.', verbose_name='نص من نحن بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='about_title_ar',
            field=models.CharField(default='من نحن', max_length=160, verbose_name='عنوان من نحن بالعربية'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='about_title_en',
            field=models.CharField(default='About Us', max_length=160, verbose_name='عنوان من نحن بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='show_about',
            field=models.BooleanField(default=True, verbose_name='إظهار قسم من نحن'),
        ),
    ]
