# Generated by Django 5.2.16 on 2026-07-30 14:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_booking_controls_and_image_sources'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('code', models.CharField(editable=False, max_length=16, unique=True, verbose_name='رقم الطلب')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('confirmed', 'مؤكد'), ('preparing', 'قيد التحضير'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغي')], default='new', max_length=20, verbose_name='الحالة')),
                ('fulfillment', models.CharField(choices=[('pickup', 'استلام من المطعم'), ('delivery', 'ديليفري')], default='pickup', max_length=20, verbose_name='طريقة الاستلام')),
                ('customer_name', models.CharField(blank=True, max_length=150, verbose_name='اسم العميل')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='رقم الجوال')),
                ('address', models.TextField(blank=True, verbose_name='عنوان التوصيل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='الإجمالي')),
                ('currency', models.CharField(default='₪', max_length=20, verbose_name='العملة')),
                ('has_unpriced_lines', models.BooleanField(default=False, verbose_name='يحتوي عرضًا يُسعّر لاحقًا')),
                ('restaurant_name', models.CharField(blank=True, max_length=120, verbose_name='اسم المطعم')),
                ('restaurant_tagline', models.CharField(blank=True, max_length=160, verbose_name='شعار المطعم')),
                ('language', models.CharField(default='ar', max_length=5, verbose_name='لغة الطلب')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='restaurant__status_be8448_idx'), models.Index(fields=['phone'], name='restaurant__phone_ba356a_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('name_ar', models.CharField(max_length=150, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='الاسم بالإنجليزية')),
                ('quantity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='سعر الوحدة')),
                ('is_priced', models.BooleanField(default=True, verbose_name='له سعر ثابت')),
                ('price_note', models.CharField(blank=True, max_length=80, verbose_name='نص السعر')),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='restaurant.menuitem', verbose_name='الطبق')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='restaurant.offer', verbose_name='العرض')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='restaurant.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'صنف في الطلب',
                'verbose_name_plural': 'أصناف الطلب',
                'ordering': ['id'],
            },
        ),
    ]
