# Generated by Django 5.2.16 on 2026-08-01 22:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_order_source_and_cashier'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsettings',
            name='deep_color',
            field=models.CharField(default='#8C1518', max_length=20, validators=[django.core.validators.RegexValidator(message='أدخل لونًا بصيغة سداسية صحيحة مثل #E30613.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='الأحمر الداكن'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='orange_color',
            field=models.CharField(default='#FF6D00', max_length=20, validators=[django.core.validators.RegexValidator(message='أدخل لونًا بصيغة سداسية صحيحة مثل #E30613.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='البرتقالي (العروض)'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='background_color',
            field=models.CharField(default='#F5F5F5', max_length=20, validators=[django.core.validators.RegexValidator(message='أدخل لونًا بصيغة سداسية صحيحة مثل #E30613.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='لون خلفية الصفحة'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='gold_color',
            field=models.CharField(default='#FFC107', max_length=20, validators=[django.core.validators.RegexValidator(message='أدخل لونًا بصيغة سداسية صحيحة مثل #E30613.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='الأصفر المميز'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='primary_color',
            field=models.CharField(default='#D71920', max_length=20, validators=[django.core.validators.RegexValidator(message='أدخل لونًا بصيغة سداسية صحيحة مثل #E30613.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='الأحمر الأساسي'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='surface_color',
            field=models.CharField(default='#FFFFFF', max_length=20, validators=[django.core.validators.RegexValidator(message='أدخل لونًا بصيغة سداسية صحيحة مثل #E30613.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='لون البطاقات'),
        ),
    ]
