# Generated by Django 5.2.16 on 2026-08-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_brand_palette_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(choices=[('fries', 'فرايز'), ('chicken', 'دجاج وستربس'), ('burger', 'برجر وساندويتش'), ('kids', 'وجبات أطفال'), ('sauce', 'صوصات'), ('salad', 'سلطات'), ('dessert', 'حلويات'), ('drink', 'مشروبات'), ('seafood', 'بحريات')], default='burger', max_length=20, verbose_name='الأيقونة'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='about_text_ar',
            field=models.TextField(default='فرايز ستيشن مكان واحد للبطاطا المقرمشة والدجاج المقلي. نقلي الطلب عند طلبه، ونصنع صوصاتنا بأنفسنا، ونقدّمها بسرعة وبنفس الجودة في كل مرة.', verbose_name='نص من نحن بالعربية'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='about_text_en',
            field=models.TextField(default='Fries Station is one place for crispy fries and fried chicken. Everything is fried to order, the sauces are our own, and the quality is the same every time.', verbose_name='نص من نحن بالإنجليزية'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='address_ar',
            field=models.CharField(blank=True, max_length=255, verbose_name='العنوان بالعربية'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='address_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='العنوان بالإنجليزية'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='featured_title_ar',
            field=models.CharField(default='الأصناف المميزة', max_length=160, verbose_name='عنوان الأطباق المميزة بالعربية'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='footer_text_ar',
            field=models.CharField(default='بطاطا مقرمشة ودجاج مقلي، تُقلى عند الطلب.', max_length=255, verbose_name='وصف التذييل بالعربية'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='footer_text_en',
            field=models.CharField(default='Crispy fries and fried chicken, cooked to order.', max_length=255, verbose_name='وصف التذييل بالإنجليزية'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='hero_text_ar',
            field=models.TextField(default='بطاطا مقرمشة ودجاج مقلي طازج، مع صوصاتنا الخاصة. سريع، طازج، ولذيذ.', verbose_name='وصف الواجهة بالعربية'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='hero_text_en',
            field=models.TextField(default='Crispy fries and freshly fried chicken, with our own sauces. Fast, fresh and delicious.', verbose_name='وصف الواجهة بالإنجليزية'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='hero_title_ar',
            field=models.CharField(default='مقرمشة. ذهبية. مثالية.', max_length=180, verbose_name='عنوان الواجهة بالعربية'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='hero_title_en',
            field=models.CharField(default='Crispy. Golden. Perfect.', max_length=180, verbose_name='عنوان الواجهة بالإنجليزية'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='hours_ar',
            field=models.CharField(default='يوميًا من 11:30 صباحًا حتى 11:30 مساءً', max_length=160, verbose_name='ساعات العمل بالعربية'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='hours_en',
            field=models.CharField(default='Daily, 11:30 AM - 11:30 PM', max_length=160, verbose_name='ساعات العمل بالإنجليزية'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='name_ar',
            field=models.CharField(default='فرايز ستيشن', max_length=120, verbose_name='اسم المطعم بالعربية'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='name_en',
            field=models.CharField(default='Fries Station', max_length=120, verbose_name='اسم المطعم بالإنجليزية'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='offers_title_ar',
            field=models.CharField(default='العروض', max_length=160, verbose_name='عنوان العروض بالعربية'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='phone',
            field=models.CharField(blank=True, max_length=40, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='tagline_ar',
            field=models.CharField(default='مقرمشة. ذهبية. مثالية.', max_length=160, verbose_name='الشعار النصي بالعربية'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='tagline_en',
            field=models.CharField(default='Crispy. Golden. Perfect.', max_length=160, verbose_name='الشعار النصي بالإنجليزية'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='أرقام فقط مع رمز الدولة، مثال: 972590000000. الطلب والحجز لا يعملان بدونه.', max_length=30, verbose_name='رقم واتساب'),
        ),
    ]
