# Generated by Django 5.2.16 on 2026-08-02 09:42

import django.core.validators
import django.db.models.deletion
import restaurant.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_fries_station_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='size_label_ar',
            field=models.CharField(blank=True, max_length=60, verbose_name='الحجم بالعربية'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='size_label_en',
            field=models.CharField(blank=True, max_length=60, verbose_name='الحجم بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='og_image_url',
            field=models.CharField(blank=True, max_length=500, validators=[restaurant.models.image_source_validator], verbose_name='رابط أو مسار صورة المشاركة البديل'),
        ),
        migrations.CreateModel(
            name='MenuItemSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('name_ar', models.CharField(max_length=60, verbose_name='اسم الحجم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=60, verbose_name='اسم الحجم بالإنجليزية')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='السعر')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('is_available', models.BooleanField(default=True, verbose_name='متاح')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='restaurant.menuitem', verbose_name='الصنف')),
            ],
            options={
                'verbose_name': 'حجم',
                'verbose_name_plural': 'الأحجام',
                'ordering': ['display_order', 'price', 'id'],
                'constraints': [models.UniqueConstraint(fields=('menu_item', 'name_ar'), name='unique_size_name_per_item')],
            },
        ),
    ]
