# Generated by Django 5.2.16 on 2026-08-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_item_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsettings',
            name='tiktok_url',
            field=models.URLField(blank=True, verbose_name='رابط تيك توك'),
        ),
    ]
